apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api
        image: us-central1-docker.pkg.dev/verdant-nova-461606-f4/my-repo/iris-api:latest
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8200
  selector:
    app: iris-api
